### ISSUE TITLE
Remove Styrene font

### ISSUE THREAD

**Issue by sreejithkaimal** [hashgraph/hedera-wallet-ios#30] opened 2019-10-23 21:15 UTC
For the time being we will not be using the Styrene font.  Please replace it with the preferred backup, Arial, unless Donald specifies a different font / sequence of fonts.

**Comment by robert-at-hedera** [comment] 2019-11-04 10:32
Closing as duplicate of #159 .

**Closed by robert-at-hedera** 2019-11-04 10:32 UTC
Labels: duplicate
